AUG:
  TEST_CROP: true
DATA:
  IMG_SIZE: 84
  NUM_WORKERS: 8
  TEST:
    BATCH_SIZE: 2
    DATASET_NAMES:
    - Birds
    DATASET_ROOTS:
    - /data1/mazc/fzy/dataset/CUB_200_2011/
    EPISODE_DESCR_CONFIG:
      MAX_NUM_QUERY: 15
      MIN_EXAMPLES_IN_CLASS: 20
      NUM_QUERY: 15
      NUM_SUPPORT: 1
      NUM_TASKS_PER_EPOCH: 10000
      NUM_WAYS: 5
      SEQUENTIAL_SAMPLING: 1
      USE_BILEVEL_HIERARCHY: false
      USE_DAG_HIERARCHY: false
GPU_ID: 0
IS_TRAIN: 0
MODEL:
  BACKBONE: resnet12
  CLASSIFIER: proto_knn_head
  NAME: evaluation_CUB_res12_5way-1shot
  PRETRAINED: /data1/mazc/fzy/115-result/CUB/PKNN-res12-pre/CUB_Res12_PNKNN_5way-1shot/main/ckpt_epoch_1_top1.pth
  TYPE: Episodic_Model_knn
OUTPUT: ./new_metadataset_result
