AUG:
  TEST_CROP: true
DATA:
  IMG_SIZE: 84
  NUM_WORKERS: 8
  TEST:
    BATCH_SIZE: 2
    DATASET_NAMES:
    - Birds
    DATASET_ROOTS:
    - /data1/jiangzhen/tn/CUB_200_2011/
    EPISODE_DESCR_CONFIG:
      MAX_NUM_QUERY: 15
      MIN_EXAMPLES_IN_CLASS: 20
      NUM_QUERY: 15
      NUM_SUPPORT: 5
      NUM_TASKS_PER_EPOCH: 1000
      NUM_WAYS: 5
      SEQUENTIAL_SAMPLING: 1
      USE_BILEVEL_HIERARCHY: false
      USE_DAG_HIERARCHY: false
GPU_ID: 3
IS_TRAIN: 0
MODEL:
  BACKBONE: resnet12
  CLASSIFIER: proto_knn_head
  NAME: CUB_5shot_lam=0.9
  PRETRAINED: /data1/jiangzhen/fzy/42-experiments/dif-weight_0.1-0.9/CUB-5shot-PKNN-res12/CUB_5shot_lam=0.9/main/ckpt_epoch_17_top1.pth
  TYPE: Episodic_Model_knn
OUTPUT: ./new_metadataset_result
