DATA:
  IMG_SIZE: 84
  NUM_WORKERS: 8
  TRAIN:
    BATCH_SIZE: 2
    DATASET_NAMES:
    - Birds
    DATASET_ROOTS:
    - /data1/jiangzhen/tn/CUB_200_2011/
    EPISODE_DESCR_CONFIG:
      MIN_EXAMPLES_IN_CLASS: 20
      NUM_QUERY: 15
      NUM_SUPPORT: 1
      NUM_TASKS_PER_EPOCH: 1000
      NUM_WAYS: 5
      USE_DAG_HIERARCHY: false
    IS_EPISODIC: true
  VALID:
    BATCH_SIZE: 8
    DATASET_NAMES:
    - Birds
    DATASET_ROOTS:
    - /data1/jiangzhen/tn/CUB_200_2011/
    EPISODE_DESCR_CONFIG:
      MAX_NUM_QUERY: 15
      MIN_EXAMPLES_IN_CLASS: 20
      NUM_QUERY: 15
      NUM_SUPPORT: 1
      NUM_TASKS_PER_EPOCH: 600
      NUM_WAYS: 5
      USE_DAG_HIERARCHY: false
GPU_ID: 3
MODEL:
  BACKBONE: resnet12
  CLASSIFIER: proto_knn_head
  NAME: CUB_1shot_lam=0.1
  TYPE: Episodic_Model_knn
OUTPUT: /data1/jiangzhen/fzy/42-experiments/dif-weight_0.1-0.9/CUB-1shot-PKNN-res12/
TRAIN:
  BASE_LR: 0.01
  EPOCHS: 80
